#+TITLE: Rootme

* nmap
┌─[root@parrot-virtual]─[~/haxx/ctf/thm/rootme]
└──╼ # nmap -sC -sV -oA nmap/scan 10.10.103.248
Starting Nmap 7.91 ( https://nmap.org  ) at 2020-11-15 07:49 EST
Nmap scan report for 10.10.103.248
Host is up (0.14s latency).
Not shown: 998 closed ports
PORT   STATE SERVICE VERSION
22/tcp open  ssh     OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey:
|   2048 4a:b9:16:08:84:c2:54:48:ba:5c:fd:3f:22:5f:22:14 (RSA)
|   256 a9:a6:86:e8:ec:96:c3:f0:03:cd:16:d5:49:73:d0:82 (ECDSA)
|_  256 22:f6:b5:a6:54:d9:78:7c:26:03:5a:95:f3:f9:df:cd (ED25519)
80/tcp open  http    Apache httpd 2.4.29 ((Ubuntu))
| http-cookie-flags:
|   /:
|     PHPSESSID:
|_      httponly flag not set
|_http-server-header: Apache/2.4.29 (Ubuntu)
|_http-title: HackIT - Home
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 23.60 seconds

* gobuster
┌─[✗]─[root@parrot-virtual]─[~/haxx/ctf/thm/rootme]
└──╼ # gobuster dir -u 10.10.103.248 -w /usr/share/wordlists/dirbuster/directory-list-2.3-small.txt
===============================================================
Gobuster v3.0.1
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@_FireFart_)
===============================================================
[+] Url:            http://10.10.103.248
[+] Threads:        10
[+] Wordlist:       /usr/share/wordlists/dirbuster/directory-list-2.3-small.txt
[+] Status codes:   200,204,301,302,307,401,403
[+] User Agent:     gobuster/3.0.1
[+] Timeout:        10s
===============================================================
2020/11/15 07:52:24 Starting gobuster
===============================================================
/uploads (Status: 301)
/css (Status: 301)
/js (Status: 301)
/panel (Status: 301)
Progress: 7505 / 87665 (8.56%)^C
[!] Keyboard interrupt detected, terminating.
===============================================================
2020/11/15 07:54:00 Finished
===============================================================

- gobuster finds a directory called uploads, sounds interesting so i check it out.
  as expected its the uploads directory.
  soon after we see that theres a directory called /panel
  with further inspection we find out that we can upload stuff onto the server.
  however it has blocked some file extensions.
  turns out we can bypass file extension authentication
  we upload a php reverse shell with the extension .php5
  apache will parse the php5 as php so were able to bypass the php blacklisting
